#!/usr/bin/env bash
# Command to Install nginx server

sudo apt-get update
sudo apt-get install nginx
sudo ufw 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

#test nginx configurations
sudo nginx -t

sudo service nginx reload
